import type { IconName } from "@/components/ui/icon";

export const featureGroups = [
  { id: "routine", label: "SEU DIA, COM DIREÇÃO", title: "Do panorama ao próximo passo.", description: "Encontre suas prioridades. Transforme intenção em constância." },
  { id: "care", label: "ESPAÇO PARA CUIDAR", title: "Aprender. Planejar. Cuidar de você.", description: "Áreas diferentes da vida, com a mesma atenção aos detalhes." },
  { id: "context", label: "MAIS CONTEXTO PARA SUA ROTINA", title: "Perceba seu ritmo. Compartilhe objetivos.", description: "Check-ins, lembretes, desafios em grupo e novas perspectivas." },
] as const;

type Feature = { name: string; icon: IconName; description: string; detail: string; className: string; group: typeof featureGroups[number]["id"]; premium?: boolean; highlights?: string[] };

export const features: Feature[] = [
  { name: "Visão geral", icon: "grid", description: "Sua rotina começa com uma visão do todo.", detail: "A Home reúne resumos de tarefas, hábitos, estudos, finanças e saúde. Veja o que merece atenção sem alternar entre vários lugares.", className: "feature-dashboard", group: "routine", highlights: ["Resumo do dia", "Áreas da vida", "Prioridades por perto"] },
  { name: "Tarefas", icon: "tasks", description: "O importante, em primeiro lugar.", detail: "Organize tarefas por prioridade, acompanhe conclusões e escolha uma delas como alvo de uma sessão de Focus.", className: "feature-tasks", group: "routine" },
  { name: "Hábitos", icon: "habits", description: "Pequenos passos. Sua própria constância.", detail: "Registre suas práticas diárias e acompanhe o histórico de dias concluídos para enxergar sua rotina ao longo do tempo.", className: "feature-habits", group: "routine" },
  { name: "Metas", icon: "goals", description: "Dê direção ao que importa.", detail: "Crie objetivos, acompanhe o progresso e mantenha o caminho que você escolheu sempre por perto.", className: "feature-goals", group: "routine" },
  { name: "Focus", icon: "focus", description: "Um momento para uma coisa de cada vez.", detail: "Use o timer com uma tarefa ou disciplina como alvo. Escolha a duração e registre suas sessões concluídas de concentração.", className: "feature-focus", group: "routine" },
  { name: "Estudos", icon: "studies", description: "Aprender. Revisar. Continuar.", detail: "Organize disciplinas e datas de provas, crie flashcards e encontre sua fila de revisão. Acompanhe o progresso e a sequência de dias de estudo.", className: "feature-studies", group: "care", highlights: ["Disciplinas e provas", "Flashcards", "Revisões e constância"] },
  { name: "Finanças", icon: "finances", description: "Clareza sobre o que entra e o que sai.", detail: "Registre receitas e despesas, organize categorias e consulte o saldo e o histórico de transações em uma visão financeira da sua rotina.", className: "feature-finances", group: "care", highlights: ["Saldo", "Receitas e despesas", "Categorias e histórico"] },
  { name: "Saúde", icon: "health", description: "Cuide da rotina de cuidar de você.", detail: "Acompanhe seu humor e a hidratação. Organize medicamentos com data de início, duração e fim do tratamento, além de lembretes. O acompanhamento do ciclo menstrual pode ser ativado nas suas preferências.", className: "feature-health", group: "care", highlights: ["Humor e hidratação", "Medicamentos e lembretes", "Ciclo opcional"] },
  { name: "Check-in", icon: "checkin", description: "Uma pausa para perceber como você está.", detail: "Registre energia, capacidade de foco e motivação em um check-in diário. Um retrato simples do seu estado, a partir da sua própria percepção.", className: "feature-checkin", group: "context" },
  { name: "Central de Notificações", icon: "bell", description: "O que merece atenção, reunido.", detail: "Consulte lembretes de hábitos, provas e medicamentos dentro do app. Acompanhe itens pendentes e concluídos na central da sua rotina.", className: "feature-notifications", group: "context" },
  { name: "Círculos", icon: "circles", description: "Objetivos em comum. Cada um no seu ritmo.", detail: "Crie um círculo ou entre em um existente. Reúna membros em desafios, acompanhe contribuições, progresso e ranking. Você pode sair quando quiser.", className: "feature-circles", group: "context" },
  { name: "Analytics", icon: "analytics", description: "Enxergue os sinais da sua constância.", detail: "No Premium, acompanhe indicadores de tarefas, hidratação, finanças e hábitos, além da evolução semanal de hábitos. São resumos dos seus registros, independentes das análises por IA.", className: "feature-analytics", group: "context", premium: true, highlights: ["Indicadores pessoais", "Evolução semanal", "Sem geração por IA"] },
  { name: "AI Companion", icon: "sparkle", description: "Uma nova perspectiva, quando você escolher.", detail: "Solicite análises do dia, da semana ou das finanças do mês a partir do contexto do Life OS. Recurso Premium, com conexão e consentimento específico, que você pode revogar.", className: "feature-ai", group: "context", premium: true },
];

export const faqs = [
  { question: "O que é o Life OS?", answer: "É um sistema integrado para organizar diferentes áreas da vida. A Home conecta uma visão da rotina a tarefas, hábitos, metas, Focus, estudos, finanças e saúde, com funcionamento offline-first e inteligência opcional." },
  { question: "Quais áreas ele organiza?", answer: "Além de tarefas, hábitos, metas, foco, estudos, finanças e saúde, o Life OS inclui check-ins de energia, foco e motivação, uma Central de Notificações e Círculos com desafios compartilhados. O Premium acrescenta analytics avançado e o AI Companion." },
  { question: "Funciona sem internet?", answer: "Os recursos pessoais suportados mantêm registros disponíveis localmente para continuar a rotina sem conexão. A sincronização acontece quando a conexão está disponível. Entrar na conta, gerar análises por IA e realizar operações online dos Círculos dependem de internet; offline-first não significa que todos os recursos funcionam desconectados." },
  { question: "Preciso de uma conta?", answer: "Sim. O acesso ao aplicativo está associado à sua conta. Você pode entrar com e-mail e senha ou com Google. Depois do acesso inicial, os recursos locais suportados permitem continuar a organização offline." },
  { question: "Como funciona a sincronização?", answer: "O Life OS guarda registros localmente e sincroniza os dados da sua conta nos módulos suportados quando há conexão. Uma alteração feita offline pode permanecer pendente até a sincronização. A disponibilidade entre dispositivos depende da conclusão desse processo." },
  { question: "O que é o AI Companion?", answer: "É um hub Premium de análises contextuais. Você escolhe analisar seu dia, sua semana ou suas finanças do mês. O recurso utiliza os resumos necessários do próprio Life OS, exige conexão e consentimento específico, e não executa decisões ou ações por você." },
  { question: "A inteligência artificial é obrigatória?", answer: "Não. Você escolhe se quer usar o AI Companion e pode revogar o consentimento no próprio recurso. Os módulos pessoais e os indicadores locais não dependem de gerar uma análise por IA." },
  { question: "O que são Círculos?", answer: "São espaços com membros e desafios em comum. Você pode criar ou entrar em um círculo, acompanhar o progresso e o ranking dos desafios e sair quando quiser. Participar não compartilha automaticamente seus registros pessoais de finanças ou saúde." },
  { question: "Como funcionam as notificações?", answer: "A Central de Notificações reúne dentro do Life OS lembretes de hábitos, provas e medicamentos, com itens pendentes e concluídos. Ela é diferente das notificações do Android, que dependem das permissões e configurações do dispositivo." },
  { question: "Qual é a diferença entre Free e Premium?", answer: "O Free dá acesso à base do Life OS dentro dos limites do plano. O Premium inclui o AI Companion, analytics avançado e limites ampliados nos recursos suportados. Preços e condições serão anunciados no lançamento; esta página não oferece assinatura, desconto ou teste grátis." },
  { question: "Quando posso baixar no Android?", answer: "O lançamento inicial é focado em Android. Enquanto a página oficial no Google Play não estiver confirmada, o site apresenta “Em breve no Google Play”, sem link de download ou data anunciada." },
  { question: "Há uma versão para iOS?", answer: "O lançamento inicial é focado em Android. Não há disponibilidade ou data de lançamento para iOS anunciada nesta etapa." },
  { question: "Como o Life OS trata privacidade e consentimento?", answer: "O produto é projetado com privacidade, consentimento e controle como princípios. O AI Companion solicita uma autorização específica, que pode ser revogada. A página de privacidade descreve comportamentos confirmados do app; a política oficial ainda depende de revisão jurídica." },
  { question: "Como excluir minha conta?", answer: "No aplicativo, abra Configurações, depois Gerenciamento da Conta e selecione Excluir Conta. Confirme sua identidade com a senha atual ou com Google, conforme o acesso utilizado. O fluxo exige conexão e só conclui após a confirmação da exclusão e da limpeza dos dados locais associados. Encerrar Sessão é uma ação diferente. Consulte a página de Exclusão de Conta para os detalhes." },
];
